from typing import Dict
from datetime import datetime

class ReportGenerator:
    @staticmethod
    def generate_markdown(analysis: Dict[str, str], proposals: Dict[str, str], output_file: str = "proposal.md"):
        content = f"# Project Proposal\nDate: {datetime.now().strftime('%Y-%m-%d')}\n\n"
        
        content += "## 1. Executive Summary\n"
        content += "This proposal outlines the technical approach, timeline, and costs for the requested project. "
        content += "It has been prepared by our staff of specialists including Full Stack Development, DevOps, Security, and Data Science.\n\n"
        
        content += "## 2. Technical Analysis\n"
        for role, text in analysis.items():
            content += f"### {role}\n{text}\n\n"
            
        content += "## 3. Detailed Estimations & Pricing\n"
        for role, text in proposals.items():
            content += f"### {role}\n{text}\n\n"
            
        content += "---\nGenerated by AI Multi-Agent System"
        
        with open(output_file, "w", encoding="utf-8") as f:
            f.write(content)
        
        return content
